<?php

namespace Tests\Feature\Console;

use App\Domains\Nexus\Business\Application\Actions\RegisterBusinessAction;
use App\Domains\Nexus\Business\Application\Actions\VerifyBusinessAction;
use App\Domains\Nexus\Business\Domain\ValueObjects\BusinessType;
use App\Domains\Nexus\Business\Domain\ValueObjects\Industry;
use App\Domains\Nexus\Catalog\Application\Actions\AddProductAction;
use App\Domains\Nexus\Contract\Domain\Repositories\ContractRepositoryInterface;
use App\Domains\Nexus\Contract\Domain\Repositories\EscrowRepositoryInterface;
use App\Domains\Nexus\Negotiation\Domain\Repositories\NegotiationRepositoryInterface;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * `nexus:demo-negotiation` — simulates a real propose->counter->accept
 * round against a real supplier Business, for watching live in the admin
 * Negotiation Monitor without needing an external Agent client wired up
 * to MCP yet. Real assertion here is that it goes all the way through to
 * an Accepted Negotiation with a real Contract + Escrow generated by the
 * same event chain a genuine MCP-driven accept() would trigger — not a
 * shortcut or a fake summary.
 */
class DemoNegotiationCommandTest extends TestCase
{
    use RefreshDatabase;

    public function test_command_negotiatesAndAcceptsAgainstARealSupplier(): void
    {
        $supplier = app(RegisterBusinessAction::class)->execute('شرکت تامین‌کننده', 'Supplier Co', BusinessType::Company, Industry::Manufacturing);
        app(VerifyBusinessAction::class)->execute($supplier->id);
        $product = app(AddProductAction::class)->execute($supplier->id, 'لوله', 'Pipe', 1_000_000, 'IRT', 10);

        $this->artisan('nexus:demo-negotiation', ['supplier' => $supplier->id])
            ->assertExitCode(0);

        $negotiations = app(NegotiationRepositoryInterface::class)->findVisibleTo($supplier->id);
        $this->assertCount(1, $negotiations);
        $negotiation = $negotiations[0];

        $this->assertSame('accepted', $negotiation->status()->value);
        $this->assertSame($supplier->id, $negotiation->counterpartyBusinessId());
        $this->assertSame($product->id, $negotiation->catalogItemId());

        $contract = app(ContractRepositoryInterface::class)->findByNegotiationId($negotiation->id());
        $this->assertNotNull($contract);

        $escrow = app(EscrowRepositoryInterface::class)->findByNegotiationId($negotiation->id());
        $this->assertNotNull($escrow);
        $this->assertSame('held', $escrow->status()->value);
    }

    public function test_command_withUnverifiedSupplier_fails(): void
    {
        $supplier = app(RegisterBusinessAction::class)->execute('شرکت تأییدنشده', 'Unverified Co', BusinessType::Company, Industry::Manufacturing);

        $this->artisan('nexus:demo-negotiation', ['supplier' => $supplier->id])
            ->assertExitCode(1);
    }

    public function test_command_withNoProducts_fails(): void
    {
        $supplier = app(RegisterBusinessAction::class)->execute('شرکت بدون‌محصول', 'Productless Co', BusinessType::Company, Industry::Manufacturing);
        app(VerifyBusinessAction::class)->execute($supplier->id);

        $this->artisan('nexus:demo-negotiation', ['supplier' => $supplier->id])
            ->assertExitCode(1);
    }
}
